### ISSUE TITLE
panic on linux when quering TimeTicks

### ISSUE THREAD

**Issue by thebinary** [thebinary/go-snmp-grpc#4]
OID: .1.3.6.1.2.1.1.3.0
Running On: Linux {host} 2.6.32-504.30.3.el6.x86_64 #1 SMP Wed Jul 15 10:13:09 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Panic logged:
panic: interface conversion: interface {} is uint32, not uint

goroutine 15 [running]:
github.com/thebinary/go-snmp-grpc/server.ToPbSnmpPDU(...)
        /home/travis/gopath/src/github.com/thebinary/go-snmp-grpc/server/helpers.go:76
github.com/thebinary/go-snmp-grpc/server.(*CommandServer).Get(0x11fbb60, 0xcd3d40, 0xc00014f830, 0xc0000456c0, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/thebinary/go-snmp-grpc/server/get.go:35 +0x857
github.com/thebinary/go-snmp-grpc/protobuf._Command_Get_Handler(0xb39440, 0x11fbb60, 0xcd3d40, 0xc00014f830, 0xc00008d4a0, 0x0, 0xcd3d40, 0xc00014f830, 0xc000039500, 0x14)
        /home/travis/gopath/src/github.com/thebinary/go-snmp-grpc/protobuf/snmp.pb.go:613 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000264680, 0xcdca60, 0xc0002af680, 0xc0001ce200, 0xc0001df710, 0x11eedc0, 0x0, 0x0, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x4db
google.golang.org/grpc.(*Server).handleStream(0xc000264680, 0xcdca60, 0xc0002af680, 0xc0001ce200, 0x0)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xd32
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00003b990, 0xc000264680, 0xcdca60, 0xc0002af680, 0xc0001ce200)
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa1

**Comment by thebinary** [comment]
fixed by commit: [f60cba1](https://github.com/thebinary/go-snmp-grpc/commit/f60cba1ef1741046d94b2b6891b7e690349e803c)
